/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "tertiary-container": "#a8a39b",
        "on-tertiary-fixed": "#1e1b16",
        "background": "#fbf9f5",
        "outline": "#817569",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e8e1d9",
        "surface-container-high": "#eae8e4",
        "secondary": "#775652",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0ed",
        "outline-variant": "#d3c4b6",
        "primary-fixed": "#ffddb9",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#2b1700",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#e7bdb8",
        "surface-variant": "#e4e2de",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad6",
        "surface-container-highest": "#e4e2de",
        "surface-bright": "#fbf9f5",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#614014",
        "on-secondary-container": "#7a5955",
        "surface-container": "#efeeea",
        "on-surface": "#1b1c1a",
        "surface": "#fbf9f5",
        "inverse-surface": "#30312e",
        "primary-container": "#c89b67",
        "on-primary-container": "#523307",
        "secondary-container": "#ffd3cd",
        "tertiary-fixed-dim": "#ccc6bd",
        "secondary-fixed": "#ffdad6",
        "on-background": "#1b1c1a",
        "on-surface-variant": "#4f453a",
        "on-secondary-fixed-variant": "#5d3f3c",
        "tertiary": "#625e57",
        "surface-container-low": "#f5f3ef",
        "primary-fixed-dim": "#eebe87",
        "inverse-primary": "#eebe87",
        "primary": "#7c572a",
        "on-tertiary-fixed-variant": "#4a4640",
        "surface-tint": "#7c572a",
        "on-secondary-fixed": "#2d1513",
        "on-tertiary-container": "#3d3933",

        brand: {
          base: "#fbf9f5",
          surface: "#f5f3ef",
          charcoal: "#1b1c1a",
          muted: "#4f453a",
          border: "#d3c4b6",
          gold: "#c89b67",
          "gold-hover": "#7c572a",
          burgundy: "#775652",
          "burgundy-hover": "#5d3f3c",
          light: "#ffffff",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "margin-tablet": "2.5rem",
        "space-3xl": "6rem",
        margin: "1.25rem",
        "gutter-desktop": "2.5rem",
        "margin-desktop": "5rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["Bodoni Moda", "serif"],
        "label-numeric": ["Manrope", "sans-serif"],
        "headline-sm": ["Bodoni Moda", "serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "display-hero-mobile": ["Bodoni Moda", "serif"],
        "display-hero": ["Bodoni Moda", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-uppercase": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "subhead-eyebrow": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        serif: ["Bodoni Moda", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-numeric": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["2rem", { lineHeight: "2.5rem", letterSpacing: "0em", fontWeight: "500" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "3.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-hero": ["5rem", { lineHeight: "5.5rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.625rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-uppercase": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "2.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "subhead-eyebrow": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.22em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.375rem", letterSpacing: "0.01em", fontWeight: "400" }],
      },
      boxShadow: {
        subtle: "0 2px 10px rgba(0, 0, 0, 0.03)",
        card: "0 4px 20px rgba(26, 26, 26, 0.05)",
        drawer: "-4px 0 24px rgba(0, 0, 0, 0.08)",
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        slideLeft: 'slideLeft 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
};
