/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9f5",
        "surface-bright": "#fdfbf7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "surface-dim": "#dbdad6",
        "primary": "#7c572a",
        "primary-container": "#c89b67",
        "primary-fixed": "#ffddb9",
        "primary-fixed-dim": "#eebe87",
        "secondary": "#4a2e2b",
        "secondary-container": "#ffd3cd",
        "secondary-fixed": "#ffdad6",
        "tertiary": "#625e57",
        "tertiary-container": "#a8a39b",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#4f453a",
        "on-primary": "#ffffff",
        "outline": "#817569",
        "outline-variant": "#d3c4b6",
        "bronze-taupe": "#ede6dc",
        "champagne-light": "#f8f5ee",

        brand: {
          base: "#fbf9f5",
          surface: "#f5f3ef",
          charcoal: "#1b1c1a",
          muted: "#4f453a",
          border: "#d3c4b6",
          gold: "#c89b67",
          "gold-hover": "#7c572a",
          burgundy: "#4a2e2b",
          "burgundy-hover": "#36201e",
          light: "#ffffff",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2.5rem",
        "margin-desktop": "5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "margin-tablet": "2.5rem",
        "space-3xl": "6rem",
        margin: "1.25rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "serif-display": ["'Bodoni Moda'", "serif"],
        "serif-editorial": ["'Cormorant Garamond'", "serif"],
        "sans-fashion": ["'Jost'", "sans-serif"],
        "sans-body": ["'Manrope'", "sans-serif"],
        "headline-lg": ["'Bodoni Moda'", "serif"],
        "headline-md": ["'Bodoni Moda'", "serif"],
        "headline-sm": ["'Bodoni Moda'", "serif"],
        "label-numeric": ["'Jost'", "sans-serif"],
        "label-uppercase": ["'Jost'", "sans-serif"],
        "subhead-eyebrow": ["'Jost'", "sans-serif"],
        "body-md": ["'Manrope'", "sans-serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
        "body-sm": ["'Manrope'", "sans-serif"],
        serif: ["'Bodoni Moda'", "Georgia", "serif"],
        sans: ["'Manrope'", "system-ui", "sans-serif"],
      },
      boxShadow: {
        subtle: "0 2px 10px rgba(0, 0, 0, 0.03)",
        card: "0 4px 20px rgba(26, 26, 26, 0.05)",
        drawer: "-4px 0 24px rgba(0, 0, 0, 0.08)",
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        slideLeft: 'slideLeft 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
};
