/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "warm-ivory": "#F8F5F0",
        "soft-sand": "#EEE7DD",
        "deep-espresso": "#2C211E",
        "muted-rose": "#A9635B",
        "terracotta": "#B86F5D",
        "champagne": "#D7B58A",
        "soft-charcoal": "#3A3532",

        "surface": "#F8F5F0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#EEE7DD",
        "surface-container": "#F8F5F0",
        "surface-container-high": "#EEE7DD",
        "surface-container-highest": "#e4e2de",
        "surface-dim": "#EEE7DD",
        "primary": "#2C211E",
        "primary-container": "#B86F5D",
        "primary-fixed": "#D7B58A",
        "primary-fixed-dim": "#A9635B",
        "secondary": "#2C211E",
        "secondary-container": "#EEE7DD",
        "secondary-fixed": "#EEE7DD",
        "tertiary": "#3A3532",
        "tertiary-container": "#EEE7DD",
        "on-surface": "#2C211E",
        "on-surface-variant": "#3A3532",
        "on-primary": "#ffffff",
        "outline": "#D7B58A",
        "outline-variant": "#EEE7DD",
        "bronze-taupe": "#EEE7DD",
        "champagne-light": "#F8F5F0",

        brand: {
          base: "#F8F5F0",
          surface: "#EEE7DD",
          charcoal: "#3A3532",
          espresso: "#2C211E",
          rose: "#A9635B",
          terracotta: "#B86F5D",
          champagne: "#D7B58A",
          sand: "#EEE7DD",
          ivory: "#F8F5F0",
          muted: "#3A3532",
          border: "rgba(44, 33, 30, 0.12)",
          gold: "#D7B58A",
          "gold-hover": "#B86F5D",
          burgundy: "#2C211E",
          "burgundy-hover": "#2C211E",
          light: "#ffffff",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2.5rem",
        "margin-desktop": "5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "margin-tablet": "2.5rem",
        "space-3xl": "6rem",
        margin: "1.25rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "serif-display": ["'Bodoni Moda'", "serif"],
        "serif-editorial": ["'Cormorant Garamond'", "serif"],
        "sans-fashion": ["'Jost'", "sans-serif"],
        "sans-body": ["'Manrope'", "sans-serif"],
        "headline-lg": ["'Bodoni Moda'", "serif"],
        "headline-md": ["'Bodoni Moda'", "serif"],
        "headline-sm": ["'Bodoni Moda'", "serif"],
        "label-numeric": ["'Jost'", "sans-serif"],
        "label-uppercase": ["'Jost'", "sans-serif"],
        "subhead-eyebrow": ["'Jost'", "sans-serif"],
        "body-md": ["'Manrope'", "sans-serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
        "body-sm": ["'Manrope'", "sans-serif"],
        serif: ["'Bodoni Moda'", "Georgia", "serif"],
        sans: ["'Manrope'", "system-ui", "sans-serif"],
      },
      boxShadow: {
        subtle: "0 2px 10px rgba(0, 0, 0, 0.03)",
        card: "0 4px 20px rgba(26, 26, 26, 0.05)",
        drawer: "-4px 0 24px rgba(0, 0, 0, 0.08)",
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        slideLeft: 'slideLeft 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        slideUp: 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
};
